import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card, FormField, Loader } from '../components';

// RenderCards component that renders posts or displays a title message when no posts are found
const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }

  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};

// Home component, which renders the main homepage with posts and user-related features
const Home = ({ user }) => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState([]);
  const [searchText, setSearchText] = useState('');
  const [searchedResults, setSearchedResults] = useState([]);

  // Fetch all posts from backend
  const fetchPosts = async () => {
    setLoading(true);
    try {
      const response = await fetch('http://localhost:8080/api/v1/community/post', {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        const result = await response.json();
        setAllPosts(result.data.reverse()); // Reverse to show the latest posts first
      }
    } catch (err) {
      alert(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  // Handle search input change
  const handleSearchChange = (e) => {
    setSearchText(e.target.value);

    const searchResult = allPosts.filter((item) =>
      item.name.toLowerCase().includes(e.target.value.toLowerCase()) ||
      item.prompt.toLowerCase().includes(e.target.value.toLowerCase())
    );
    setSearchedResults(searchResult);
  };

  // Render user profile dropdown
  const renderProfileDropdown = () => (
    <div className="relative">
      <button className="font-medium bg-gray-200 text-black px-4 py-2 rounded-md focus:outline-none">
        {user.username} ▼
      </button>
      <div className="absolute right-0 mt-2 w-48 bg-white border rounded shadow-lg">
        <p className="px-4 py-2 text-sm text-gray-700">Email: {user.email}</p>
        <p className="px-4 py-2 text-sm text-gray-700">Username: {user.username}</p>
        <div className="border-t border-gray-200"></div>
        <button className="w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-gray-100">
          Logout
        </button>
      </div>
    </div>
  );

  return (
    <section className="max-w-7xl mx-auto">
      {/* Header section */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
          <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
            Browse through a collection of imaginative and visually stunning images generated by DALL-E AI
          </p>
        </div>

        {/* Top-right section: Profile and community buttons */}
        <div className="flex items-center space-x-4">
          {user && (
            <>
              <Link
                to="/community"
                className="font-inter font-medium bg-[#6469ff] text-white px-4 py-2 rounded-md"
              >
                Community
              </Link>
              <Link
                to="/create-post"
                className="font-inter font-medium bg-[#6469ff] text-white px-4 py-2 rounded-md"
              >
                Create Post
              </Link>

              {/* Profile dropdown */}
              {renderProfileDropdown()}
            </>
          )}
        </div>
      </div>

      {/* Search field */}
      <div className="mt-16">
        <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search something..."
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>

      {/* Posts grid */}
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing Results for <span className="text-[#222328]">{searchText}</span>:
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards data={searchedResults} title="No Search Results Found" />
              ) : (
                <RenderCards data={allPosts} title="No Posts Yet" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
